security:
  oauth2:
    client:
      clientId: 343053768739-6q6jsme8kvni4e8bmb3i855pt7orfp2a.apps.googleusercontent.com
      clientSecret: DhdlpB51pVm2NE38e93FCtT9
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        openid,
        email,
        profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true